# Generated by Django 6.0.4 on 2026-04-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=100)),
                ('categorie_prod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id_vendeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_vendeur', models.CharField(max_length=100)),
                ('prenom_vendeur', models.CharField(max_length=100)),
                ('zone_vendeur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id_objectif', models.AutoField(primary_key=True, serialize=False)),
                ('mois', models.CharField(max_length=20)),
                ('montant_cible', models.FloatField()),
                ('id_vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramasama.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='ramasama.produit')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='ramasama.vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
            },
        ),
    ]
