# Generated by Django 6.0.4 on 2026-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramasama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
